version: '3'
services:
  db:
    image: container-registry.oracle.com/database/express
    ports:
      - 1521:1521
    environment:
      - ORACLE_PWD=OraclePwd

  cli:
    build: .
    image: oraclegocli
    tty: true
    command: sh

  go-ora:
    build:
      context: .
      dockerfile: Dockerfile.go-ora
    image: go-ora:local
    tty: true
    command: sh

  go-oci8:
    build:
      context: .
      dockerfile: Dockerfile.go-oci8
    image: go-oci8:local
    tty: true
    command: sh

